apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dotnet-api
  name: dotnet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: smehrens/dotnetapi:0.0.5
        name: dotnetapi
      - command:
        - sh
        - -c
        - while true; do curl -s http://localhost/weatherforecast; sleep 5; done;
        image: nginx
        name: nginx